In [1]:
# import libraries
import numpy as np
import time
import math

In [2]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [9]:
# Vectorization (Example 1)
a = np.random.rand(10000000)
b = np.random.rand(10000000)

# vectorization
tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorization: " + str(10000*(toc-tic)) + " ms")
print(c)

# non-vectorized
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()
print("For Loop (Non-Vectorized): " + str(10000*(toc-tic)) + " ms")
print(c)

Vectorization: 89.7526741027832 ms
2499034.6902586417
For Loop (Non-Vectorized): 8336.653709411621 ms
249975.7481441315


In [10]:
# Vectorization (Example 2)

v = np.random.rand(100000)

# non-vectorized example 2
u = np.zeros((len(v), 1))
tic = time.time()
for i in range(len(v)):
    u[i] = math.exp(v[i])
print(u)
toc = time.time()
print("For Loop (Non-Vectorized): " + str(10000*(toc-tic)) + " ms\n\n")

# vectorizing example 2
u = np.zeros((len(v), 1))
tic = time.time()
u = np.exp(v)
toc = time.time()
print("Vectorization: " + str(10000*(toc-tic)) + " ms")

print(u)

[[1.04354653]
 [1.1623615 ]
 [1.9175939 ]
 ...
 [1.84723285]
 [1.28365007]
 [1.48605347]]
For Loop (Non-Vectorized): 1190.1617050170898 ms


Vectorization: 20.012855529785156 ms
[1.04354653 1.1623615  1.9175939  ... 1.84723285 1.28365007 1.48605347]
